module.exports = [
    {
      id: 1,
      productName: 'Pair Christmas Sweater',
      description: ' long sleeves, round neck, soft and elastic, warm winter clothes. The O-neck design can highlight your charming clavicle and show a good figure. Thanks to the loose design, it can accommodate various figures. It is a casual and comfortable T-shirt sweater. Because the fabric is comfortable, it can directly touch the skin. The rainbow-like color blocks collide to create a perfect wool pullover top, which is really cute.',
      category: 'sweater',
      color: 'black',
      picUrlPath: '/product/1.jpg',
      likes: '25',
      stock: '156',
      price: '50'
    },
    {
        id: 2,
        productName: 'Beautiful green sweater',
        description: 'This casual long sleeve sweater is suitable for everyday, family, outing, party, work, casual wear and other occasions. This basic classic winter top can perfectly solve the problem of what you need to wear today when it is in your wardrobe. This ladys casual loose top is available in a variety of styles and color block colors to suit your personal style',
        category: 'sweater',
        color: 'green',
        picUrlPath: '/product/2.jpg',
        likes: '2906',
        stock: '176',
        price: '20'
    },
    {
        id: 3,
        productName: 'Christmas baby sweater',
        description: 'This winter casual long-sleeved color block sweatshirt has a soft, warm fabric and shows good quality. The fabric is thick and comfortable, which can be close to the skin. You can match necklaces and coats, suitable for women of different ages and show different styles.',
        category: 'sweater',
        color: 'red',
        picUrlPath: '/product/3.jpg',
        likes: '23',
        stock: '150',
        price: '30'
    },
    {
        id: 4,
        productName: 'Reindeer Christmas sweater with beanie cap',
        description: 'This Christmas shirt showcases our talented graphic designers!',
        category: 'sweater',
        color: 'red',
        picUrlPath: '/product/4.jpg',
        likes: '27',
        stock: '146',
        price: '25'
    },
    {
        id: 5,
        productName: 'Christmas dog sweater',
        description: 'Featuring a stunning color, vibrant graphic, super-soft material, this shirt is just to die for.',
        category: 'sweater',
        color: 'red',
        picUrlPath: '/product/5.jpg',
        likes: '55',
        stock: '152',
        price: '32'
    },
    {
        id: 6,
        productName: 'Designer christmas sweater',
        description: 'MATERIAL: 95% Polyester /5% spandex. christmas sweaters has soft and cozy fabric, comfy to wear.',
        category: 'sweater',
        color: 'red',
        picUrlPath: '/product/6.jpg',
        likes: '22',
        stock: '126',
        price: '100'
    },
    {
        id: 7,
        productName: 'Max mit Christmas Stockings, Hanging',
        description: 'Decorations Xmas Sock 4Pack Christmas Stockings 10" with 3D Santa Snowman Bear Reindeer Xmas Stockings for Christmas Tree Fireplace Hanging and Party Decor',
        category: 'decor',
        color: '',
        picUrlPath: '/product/7.jpg',
        likes: '1125',
        stock: '16',
        price: '10'
    },
    {
        id: 8,
        productName: '24 Mini Glitter Christmas Tree Balls',
        description: 'Hanging Ornaments Decorative Xmas Tree Balls, Shatterproof Plastic Festive Holiday Decor Balls, Shiny, Matte & Frosted Ball Ornaments, Gold',
        category: 'decor',
        color: '',
        picUrlPath: '/product/8.jpg',
        likes: '790',
        stock: '600',
        price: '5'
    },
    {
        id: 9,
        productName: 'Christmas Inflatable Outdoor Decor',
        description: 'The giant inflatable Santa with build-in LED, the eye-catching bright pure white LED lights make it brighter, with the powerful air blower making your outside display shine during the dark night, attracting passers-by to stop by.',
        category: 'decor',
        color: '',
        picUrlPath: '/product/9.jpg',
        likes: '225',
        stock: '500',
        price: '55'
    },
    {
        id: 10,
        productName: '12 Inch Artificial Christmas Wreath',
        description: '12 Inch Artificial Christmas Wreath for Front Door Decor, Indoor and Outdoor Holiday Hanging Decoration, White and Gold Bows',
        category: 'decor',
        color: '',
        picUrlPath: '/product/10.jpg',
        likes: '428',
        stock: '156',
        price: '35'
    },
    {
        id: 11,
        productName: 'Solar System Crystal Ball',
        description: 'Made of optically clear crystal. Inspected to ensure quality and free from bubbles, imperfections.',
        category: 'gift',
        color: '',
        picUrlPath: '/product/11.jpg',
        likes: '25',
        stock: '15',
        price: '100'
    },
    {
        id: 12,
        productName: 'No Face with Night Lamp',
        description: 'Decoration home and garden: Funny mini carton no face man with night light decorate for miniature home mini garden micro landscape.',
        category: 'gift',
        color: '',
        picUrlPath: '/product/12.jpg',
        likes: '2500',
        stock: '116',
        price: '200'
    },
    {
        id: 13,
        productName: 'Insulated Wine Tumbler with Straw and Lid',
        description: 'Double wall tumbler with BPA free sealing lid will keep your drinks cold for more than 9+ hours and hot for more than 3 hours, enjoy the iced cocktails, wine, whiskey, soda, cola, beer, juice, iced coffee in the hot summer while drink warm coffee and hot tea in the cold winter, that will be a great gifts for female.',
        category: 'gift',
        color: '',
        picUrlPath: '/product/13.jpg',
        likes: '2',
        stock: '1156',
        price: '49'
    },
    {
        id: 14,
        productName: 'Song Art Glass Plaque Light up Spotify Plaque Christmas Gifts',
        description: 'Custom Spotify art plaque with scannable Spotify code! These make the perfect gift and room decor plus easily fit inside a picture frame!',
        category: 'gift',
        color: '',
        picUrlPath: '/product/14.jpg',
        likes: '2500005',
        stock: '6',
        price: '250'
    },
    {
        id: 15,
        productName: 'Custom Camera Roll Pictures Keychain',
        description: 'Custom Picture Photo Keychain Film Camera Roll Multiphoto Gift , you have got the great gift for your wife, girlfriend, family or friends.',
        category: 'gift',
        color: '',
        picUrlPath: '/product/15.png',
        likes: '225',
        stock: '87',
        price: '39'
    },
  ];